---
title: "VTI Analysis"
date: "`r Sys.Date()`"
output: 
  html_document:
    css: Report.css
---

```{r knitr_init, echo=FALSE, cache=FALSE,warning=FALSE,message=FALSE}
library(knitr)
library(rmdformats)
library(kableExtra)
## Global options
opts_chunk$set(echo=FALSE,
	             cache=FALSE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=1500)
options(knitr.table.format = "html") 
options(max.print=999999999)
temp <-tempdir()
computer.name <- Sys.info()["nodename"]
```

```{r include=FALSE,warning=FALSE,message=FALSE}
# Load Trained Model
  load("~/R/RForest_EquitiesPredict/VTI/MODEL_10.9.17.Rdata")

# Load Function Library
  source("~/R/RForest_EquitiesPredict/LIB/RF_FX_lib.R")

# Model Prediction
  pred <- stock.RF.predict(mod)

# Model Performance
  perf <- stock.RF.performance(predict.obj=pred,sell.max = -0.01,stay.max = 0.01,buy.max = 99,sell.t=0.6,buy.t=0.6)

# Model Policy
  pol <- policy.test(perf)
```

```{r}
# Create Prediction Data Frame (Table)
  prediction <- cbind.data.frame(Date=perf$predict.data$Date,
                                 Close=perf$predict.data$VTI.Close.raw,
                                 perf$probs,
                                 perf$S.ST.B[,-4],
                                 perf$Performance)
  prediction <- arrange(prediction,desc(Date))
  prediction[,3:14] <- round(prediction[,3:14],3)

#Create email cues and summary
  tab <- prediction[1,c("Date","Close","SELL","STAY","BUY","Pred.Action")]
  tab[,3:5]  <- round(tab[,3:5],3)
  tab        <- t(tab)
  tab2       <- cbind(rownames(tab),tab)
  tab3       <- apply(tab2,1,paste,collapse=" : ")
  names(tab3) <- NULL
  tab3 <- t(t(tab3))
  tab.email.t <- paste0(tab3,"\n")
  tab.email.t <- paste(tab.email.t,collapse="")
  
  WARNING.SELL.VTI <- FALSE
  if(prediction$Pred.Action[1]=="SELL") {WARNING.SELL.VTI <- TRUE}
  WARNING.BUY.VTI <- FALSE
  if(prediction$Pred.Action[1]=="BUY")  {WARNING.BUY.VTI <- TRUE}
```

# Model Prediction

```{r}
kable(cbind(Daysback=0:-39,prediction[1:40,]),bootstrap=T) %>% kableExtra::kable_styling(bootstrap_options = c("striped", "hover"))
```

# Prediction Error

```{r}
options(width = 10000)
print(perf$Prediction.Error.matrix)
```

# Actual Direction Error

```{r}
print(perf$Actual.Direction.Error.matrix)
```

# Action Error

```{r}
print(perf$Action.Error.matrix)
```
# Error Rates Summary

```{r}
print(round(perf$`Error Rates`,2))
```

```{r}
# Save Predicted Data from Last Run
write.csv(pred$predict.data,"~/R/RForest_EquitiesPredict/VTI/HistoricalData/VTI_pred_data.csv")
```

# Plot of predicted postions based on policy

```{r}
# 40 days back
  p.df <- pol$policy.predict
  p.df <- p.df[nrow(p.df):(nrow(p.df)-40),]
  p.df <- arrange(p.df,Date)
  p.df$Date <- as.Date(as.character(p.df$Date))
  
  p1 <- ggplot(data=p.df,aes(x=Date,y=Close.price)) + scale_color_manual(values=rev(hue_pal()(2)))  + geom_vline(mapping=aes(xintercept = Date,color=Position),size=2) + geom_line(size=1.5) + theme_bw() +ggtitle("40 days back") 
  p1

# 6 mo back
  p.df <- pol$policy.predict
  p.df <- p.df[nrow(p.df):(nrow(p.df)-150),]
  p.df <- arrange(p.df,Date)
  p.df$Date <- as.Date(as.character(p.df$Date))
  
  p1 <- ggplot(data=p.df,aes(x=Date,y=Close.price)) + scale_color_manual(values=rev(hue_pal()(2))) + geom_vline(mapping=aes(xintercept = Date,color=Position),size=2) + geom_line(size=1.5) + theme_bw() +ggtitle("150 days back") + scale_color_manual(values=hue_pal()(2))
  p1

# One Year Back
  p.df <- pol$policy.predict
  p.df <- p.df[nrow(p.df):(nrow(p.df)-365),]
  p.df <- arrange(p.df,Date)
  p.df$Date <- as.Date(as.character(p.df$Date))
  
  p1 <- ggplot(data=p.df,aes(x=Date,y=Close.price)) + scale_color_manual(values=rev(hue_pal()(2))) + geom_vline(mapping=aes(xintercept = Date,color=Position),size=2) + geom_line(size=1.5) + theme_bw() +ggtitle("One year back") + scale_color_manual(values=hue_pal()(2))
  p1

# All data
  p.df <- pol$policy.predict
  p.df <- arrange(p.df,Date)
  p.df$Date <- as.Date(as.character(p.df$Date))
  
  p1 <- ggplot(data=p.df,aes(x=Date,y=Close.price)) + scale_color_manual(values=rev(hue_pal()(2))) + geom_vline(mapping=aes(xintercept = Date,color=Position),size=2) + geom_line(size=0.5) + theme_bw() +ggtitle("All Data") + scale_color_manual(values=hue_pal()(2))
  p1
```

# Daily Intraday Trading Report

```{r}
VTI.ID <- Intraday("https://finance.google.com/finance/getprices?q=VTI&x=NYSEARCA&i=60&p=1d&f=d,c,h,l,o,v")
plot(VTI.ID$CLOSE)
barChart(VTI.ID,theme='white.mono',bar.type='hlc')
```

